const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { generatePassword } = require('../utils/passwordGenerator');

const UserSchema = new mongoose.Schema({
  username: {
    type: String,
    required: [true, 'Please add a username'],
    unique: true,
    trim: true,
    maxlength: [50, 'Username cannot be more than 50 characters']
  },
  email: {
    type: String,
    required: [true, 'Please add an email'],
    unique: true,
    match: [
      /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
      'Please add a valid email'
    ]
  },
  password: {
    type: String,
    required: [true, 'Please add a password'],
    minlength: [6, 'Password must be at least 6 characters'],
    select: false
  },
  autoGeneratedPassword: {
    type: String,
    select: false
  },
  isPasswordChanged: {
    type: Boolean,
    default: false
  },
  firstName: {
    type: String,
    required: [true, 'Please add a first name'],
    trim: true,
    maxlength: [50, 'First name cannot be more than 50 characters']
  },
  lastName: {
    type: String,
    required: [true, 'Please add a last name'],
    trim: true,
    maxlength: [50, 'Last name cannot be more than 50 characters']
  },
  role: {
    type: String,
    enum: ['super_admin', 'admin', 'garage_staff', 'transport_staff', 'inventory_staff', 'driver', 'customer_care'],
    default: 'admin'
  },
  route: {
    type: String,
    enum: ['kampala-nairobi', 'goma-kampala', 'nairobi-kigali', 'kampala-kigali', 'kampala-juba', 'juba-bor', 'none'],
    default: 'none'
  },
  fleetType: {
    type: String,
    enum: ['active', 'maintenance', 'both'],
    default: 'both'
  },
  department: {
    type: String,
    enum: ['management', 'garage', 'transport', 'inventory', 'drivers', 'customer_care'],
    required: [true, 'Please specify department']
  },
  terminal: {
    type: String,
    enum: ['Kigali', 'Kampala', 'Nairobi', 'Juba'],
    required: [true, 'Terminal is required']
  },
  phone: {
    type: String,
    trim: true,
    maxlength: [20, 'Phone number cannot be more than 20 characters']
  },
  avatar: {
    type: String,
    default: 'default-avatar.png'
  },
  isActive: {
    type: Boolean,
    default: true
  },
  lastLogin: {
    type: Date
  },
  loginAttempts: {
    type: Number,
    default: 0
  },
  lockUntil: {
    type: Date
  },
  permissions: {
    garage: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    },
    inventory: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    },
    assets: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    },
    personnel: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    },
    transport: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    },
    reports: {
      view: { type: Boolean, default: true },
      create: { type: Boolean, default: false },
      export: { type: Boolean, default: false }
    },
    users: {
      view: { type: Boolean, default: false },
      create: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false }
    }
  },
  resetPasswordToken: String,
  resetPasswordExpire: Date,
  emailVerificationToken: String,
  emailVerificationExpire: Date,
  isEmailVerified: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Virtual for full name
UserSchema.virtual('fullName').get(function() {
  return `${this.firstName} ${this.lastName}`;
});



// Index for better query performance
UserSchema.index({ email: 1 });
UserSchema.index({ username: 1 });
UserSchema.index({ role: 1 });
UserSchema.index({ department: 1 });
UserSchema.index({ isActive: 1 });

// Encrypt password using bcrypt
UserSchema.pre('save', async function(next) {
  if (!this.isModified('password')) {
    next();
  }

  const salt = await bcrypt.genSalt(parseInt(process.env.BCRYPT_ROUNDS) || 12);
  this.password = await bcrypt.hash(this.password, salt);
});

// Auto-generate password for new users
UserSchema.pre('save', async function(next) {
  if (this.isNew && !this.password) {
    const autoPassword = generatePassword(10);
    this.autoGeneratedPassword = autoPassword;
    this.password = autoPassword;
    this.isPasswordChanged = false;
  }
  next();
});

// Set default permissions based on role
UserSchema.pre('save', function(next) {
  if (this.isModified('role')) {
    this.setDefaultPermissions();
  }
  next();
});

// Sign JWT and return
UserSchema.methods.getSignedJwtToken = function() {
  return jwt.sign(
    { id: this._id },
    process.env.JWT_SECRET,
    { expiresIn: process.env.JWT_EXPIRE }
  );
};

// Match user entered password to hashed password in database
UserSchema.methods.matchPassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

// Check if user is locked
UserSchema.methods.checkIsLocked = function() {
  return !!(this.lockUntil && this.lockUntil > Date.now());
};

// Increment login attempts
UserSchema.methods.incLoginAttempts = function() {
  // If we have a previous lock that has expired, restart at 1
  if (this.lockUntil && this.lockUntil < Date.now()) {
    return this.updateOne({
      $unset: { lockUntil: 1 },
      $set: { loginAttempts: 1 }
    });
  }
  
  const updates = { $inc: { loginAttempts: 1 } };
  
  // Lock account after 5 failed attempts
  if (this.loginAttempts + 1 >= 5 && !this.checkIsLocked()) {
    updates.$set = { lockUntil: Date.now() + 2 * 60 * 60 * 1000 }; // 2 hours
  }
  
  return this.updateOne(updates);
};

// Reset login attempts
UserSchema.methods.resetLoginAttempts = function() {
  return this.updateOne({
    $unset: { loginAttempts: 1, lockUntil: 1 }
  });
};

  // Set default permissions based on role
  UserSchema.methods.setDefaultPermissions = function() {
    const rolePermissions = {
      admin: {
        garage: { view: true, create: true, edit: true, delete: true },
        inventory: { view: true, create: true, edit: true, delete: true },
        assets: { view: true, create: true, edit: true, delete: true },
        personnel: { view: true, create: true, edit: true, delete: true },
        transport: { view: true, create: true, edit: true, delete: true },
        reports: { view: true, create: true, export: true },
        users: { view: true, create: true, edit: true, delete: true }
      },
      staff: {
        garage: { view: true, create: false, edit: false, delete: false },
        inventory: { view: true, create: false, edit: false, delete: false },
        assets: { view: true, create: false, edit: false, delete: false },
        personnel: { view: true, create: false, edit: false, delete: false },
        transport: { view: true, create: false, edit: false, delete: false },
        reports: { view: true, create: false, export: false },
        users: { view: false, create: false, edit: false, delete: false }
      },
      driver: {
        garage: { view: false, create: false, edit: false, delete: false },
        inventory: { view: false, create: false, edit: false, delete: false },
        assets: { view: true, create: false, edit: false, delete: false },
        personnel: { view: false, create: false, edit: false, delete: false },
        transport: { view: true, create: true, edit: true, delete: false },
        reports: { view: false, create: false, export: false },
        users: { view: false, create: false, edit: false, delete: false }
      },
      garage_staff: {
        garage: { view: true, create: true, edit: true, delete: false },
        inventory: { view: true, create: true, edit: true, delete: false },
        assets: { view: true, create: false, edit: true, delete: false },
        personnel: { view: false, create: false, edit: false, delete: false },
        transport: { view: false, create: false, edit: false, delete: false },
        reports: { view: true, create: true, export: false },
        users: { view: false, create: false, edit: false, delete: false }
      },
      fuel_station_staff: {
        garage: { view: false, create: false, edit: false, delete: false },
        inventory: { view: true, create: true, edit: true, delete: false },
        assets: { view: true, create: false, edit: false, delete: false },
        personnel: { view: false, create: false, edit: false, delete: false },
        transport: { view: true, create: false, edit: false, delete: false },
        reports: { view: true, create: true, export: false },
        users: { view: false, create: false, edit: false, delete: false }
      }
    };

    this.permissions = rolePermissions[this.role] || rolePermissions.staff;
  };

// Check if user has permission for a specific action
UserSchema.methods.hasPermission = function(module, action) {
  if (!this.permissions[module]) {
    return false;
  }
  return this.permissions[module][action] || false;
};

// Check if user needs to change password
UserSchema.methods.needsPasswordChange = function() {
  return !this.isPasswordChanged;
};

// Mark password as changed
UserSchema.methods.markPasswordChanged = function() {
  this.isPasswordChanged = true;
  this.autoGeneratedPassword = undefined;
  return this.save();
};

module.exports = mongoose.model('User', UserSchema); 