import React, { useState, useEffect } from 'react';
import { RoleBasedAccess } from '../../components/RoleBasedAccess';
import { usersAPI, terminalsAPI } from '../../services/api';
import './Users.css';

const Users = () => {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [roleFilter, setRoleFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalUsers, setTotalUsers] = useState(0);

  const [showAddForm, setShowAddForm] = useState(false);
  const [showEditForm, setShowEditForm] = useState(false);
  const [showPasswordChangeForm, setShowPasswordChangeForm] = useState(false);
  const [selectedUser, setSelectedUser] = useState(null);
  const [editingUser, setEditingUser] = useState(null);
  const [newUser, setNewUser] = useState({
    username: '',
    firstName: '',
    lastName: '',
    email: '',
    role: 'admin',
    terminal: 'Kigali',
    terminalId: '',
    department: 'management',
    phone: ''
  });

  const [passwordChange, setPasswordChange] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  });

  // Terminals state
  const [terminals, setTerminals] = useState([
    { _id: 'Kigali', name: 'Kigali' },
    { _id: 'Kampala', name: 'Kampala' },
    { _id: 'Juba', name: 'Juba' },
    { _id: 'Nairobi', name: 'Nairobi' }
  ]);

  // Fetch terminals from backend (fallback to defaults on error)
  useEffect(() => {
    const loadTerminals = async () => {
      try {
        const res = await terminalsAPI.getAll();
        const list = res?.data || res?.terminals || res || [];
        if (Array.isArray(list) && list.length > 0) {
          setTerminals(list.map(t => ({ _id: t._id || t.id || t.code || t.name, name: t.name || t.code || t.label || t })));
        }
      } catch (e) {
        console.warn('Terminals fetch failed, using defaults');
      }
    };
    loadTerminals();
  }, []);

  // Fetch users from API
  const fetchUsers = async () => {
    try {
      setLoading(true);
      const params = {};
      
      // Only add parameters that have valid values
      if (currentPage) params.page = currentPage;
      if (searchTerm && searchTerm.trim()) params.search = searchTerm.trim();
      if (roleFilter && roleFilter !== 'all') params.role = roleFilter;
      if (statusFilter && statusFilter !== 'all') params.isActive = statusFilter === 'active';

      console.log('🔍 Fetching users with params:', params);
      console.log('👤 Current user from localStorage:', JSON.parse(localStorage.getItem('user') || '{}'));
      
      const response = await usersAPI.getAll(params);
      console.log('📊 Users API response:', response);
      
      // Debug password fields
      if (response.users && response.users.length > 0) {
        console.log('🔐 Password debug for first user:', {
          autoGeneratedPassword: response.users[0].autoGeneratedPassword,
          isPasswordChanged: response.users[0].isPasswordChanged,
          user: response.users[0].username
        });
      }
      
      setUsers(response.users || []);
      setTotalPages(response.totalPages || 1);
      setTotalUsers(response.totalUsers || 0);
    } catch (err) {
      console.error('❌ Error fetching users:', err);
      setError(err.message || 'Failed to fetch users');
    } finally {
      setLoading(false);
    }
  };

  // Load users on component mount and when filters change
  useEffect(() => {
    fetchUsers();
  }, [currentPage, searchTerm, roleFilter, statusFilter]);

  // Handle search with debounce
  useEffect(() => {
    const timer = setTimeout(() => {
      if (searchTerm !== '') {
        setCurrentPage(1);
        fetchUsers();
      }
    }, 500);

    return () => clearTimeout(timer);
  }, [searchTerm]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setNewUser(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleTerminalChange = (e) => {
    const value = e.target.value;
    const selected = terminals.find(t => String(t._id) === String(value) || t.name === value);
    setNewUser(prev => ({
      ...prev,
      terminal: selected?.name || value,
      terminalId: selected?._id || ''
    }));
  };

  const handlePasswordChange = (e) => {
    const { name, value } = e.target;
    setPasswordChange(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const payload = { ...newUser };
      if (!payload.terminalId) {
        const selected = terminals.find(t => t.name === payload.terminal);
        if (selected) payload.terminalId = selected._id;
      }
      const response = await usersAPI.create(payload);
      if (response.success) {
        // Show the auto-generated password to the admin
        const passwordMessage = response.autoGeneratedPassword 
          ? `User created successfully!\n\nAuto-generated password: ${response.autoGeneratedPassword}\n\nPlease share this password with the user. They will be prompted to change it on first login.`
          : 'User created successfully!';
        
        alert(passwordMessage);
        
        setNewUser({
          username: '',
          firstName: '',
          lastName: '',
          email: '',
          role: 'admin',
          terminal: 'Kigali',
          terminalId: '',
          department: 'management',
          phone: ''
        });
        setShowAddForm(false);
        fetchUsers(); // Refresh the list
      } else {
        alert('Error creating user: ' + (response.message || 'Unknown error'));
      }
    } catch (err) {
      console.error('Error creating user:', err);
      alert('Error creating user: ' + (err.message || 'Unknown error'));
    }
  };

  const handlePasswordChangeSubmit = (e) => {
    e.preventDefault();
    
    if (passwordChange.newPassword !== passwordChange.confirmPassword) {
      alert('New passwords do not match!');
      return;
    }

    if (passwordChange.newPassword.length < 6) {
      alert('New password must be at least 6 characters long!');
      return;
    }

    // For now, just show success message
    // In a real implementation, you'd call an API to change the password
    alert('Password change functionality will be implemented with backend API');
    
    setPasswordChange({
      currentPassword: '',
      newPassword: '',
      confirmPassword: ''
    });
    setShowPasswordChangeForm(false);
    setSelectedUser(null);
  };

  const handleEditUser = (user) => {
    setEditingUser(user);
    setShowEditForm(true);
  };

  const handleUpdateUser = async (e) => {
    e.preventDefault();
    try {
      // Ensure we send terminalId too
      const payload = { ...editingUser };
      const selected = terminals.find(t => t.name === payload.terminal || String(t._id) === String(payload.terminalId));
      if (selected) {
        payload.terminal = selected.name;
        payload.terminalId = selected._id;
      }
      const response = await usersAPI.update(editingUser._id, payload);
      if (response.success) {
        alert('User updated successfully!');
        setShowEditForm(false);
        setEditingUser(null);
        fetchUsers(); // Refresh the list
      } else {
        alert('Error updating user: ' + (response.message || 'Unknown error'));
      }
    } catch (err) {
      console.error('Error updating user:', err);
      alert('Error updating user: ' + (err.message || 'Unknown error'));
    }
  };

  const handleDeleteUser = async (userId) => {
    if (!window.confirm('Are you sure you want to delete this user? This action cannot be undone.')) {
      return;
    }

    try {
      const response = await usersAPI.delete(userId);
      if (response.success) {
        alert('User deleted successfully!');
        fetchUsers(); // Refresh the list
      } else {
        alert('Error deleting user: ' + (response.message || 'Unknown error'));
      }
    } catch (err) {
      console.error('Error deleting user:', err);
      alert('Error deleting user: ' + (err.message || 'Unknown error'));
    }
  };

  const generateAutoPassword = () => {
    const charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let password = '';
    for (let i = 0; i < 8; i++) {
      password += charset[Math.floor(Math.random() * charset.length)];
    }
    return password;
  };

  const getRoleBadgeClass = (role) => {
    const roleClasses = {
      'super_admin': 'badge-super-admin',
      'admin': 'badge-manager',
      'garage_staff': 'badge-garage',
      'transport_staff': 'badge-transport',
      'inventory_staff': 'badge-inventory',
      'driver': 'badge-driver',
      'customer_care': 'badge-customer'
    };
    return roleClasses[role] || 'badge-default';
  };

  const getTerminalBadgeClass = (terminal) => {
    const terminalClasses = {
      'Kigali': 'badge-kigali',
      'Kampala': 'badge-kampala',
      'Juba': 'badge-juba',
      'Nairobi': 'badge-nairobi'
    };
    return terminalClasses[terminal] || 'badge-default';
  };

  const formatRole = (role) => {
    return role.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase());
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  const openPasswordChangeForm = (user) => {
    setSelectedUser(user);
    setShowPasswordChangeForm(true);
  };

  if (loading) {
    return (
      <div className="loading-state">
        <div className="loading-spinner"></div>
        <p>Loading users...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="error-state">
        <p>Error: {error}</p>
        <button onClick={fetchUsers} className="retry-btn">Retry</button>
      </div>
    );
  }

  return (
    <RoleBasedAccess user={JSON.parse(localStorage.getItem('user') || '{}')} module="users" action="view">
      <div className="users-container">
        <div className="users-header">
          <h2>User Management</h2>
          <div className="header-actions">
            <div className="search-filters">
              <input
                type="text"
                placeholder="Search users..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="search-input"
              />
              <select
                value={roleFilter}
                onChange={(e) => setRoleFilter(e.target.value)}
                className="filter-select"
              >
                <option value="all">All Roles</option>
                <option value="super_admin">Super Admin</option>
                <option value="admin">Admin</option>
                <option value="garage_staff">Garage Staff</option>
                <option value="transport_staff">Transport Staff</option>
                <option value="inventory_staff">Inventory Staff</option>
                <option value="driver">Driver</option>
                <option value="customer_care">Customer Care</option>
              </select>
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="filter-select"
              >
                <option value="all">All Status</option>
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
              </select>
            </div>
            <RoleBasedAccess user={JSON.parse(localStorage.getItem('user') || '{}')} module="users" action="create">
              <button 
                className="add-user-btn"
                onClick={() => setShowAddForm(true)}
              >
                Add User
              </button>
            </RoleBasedAccess>
          </div>
        </div>

        <div className="users-stats">
          <div className="stat-card">
            <h3>Total Users</h3>
            <span className="stat-number">{totalUsers}</span>
          </div>
          <div className="stat-card">
            <h3>Active Users</h3>
            <span className="stat-number">{users.filter(u => u.isActive).length}</span>
          </div>
          <div className="stat-card">
            <h3>Page {currentPage} of {totalPages}</h3>
            <span className="stat-number">{users.length} shown</span>
          </div>
        </div>

        <div className="users-content">
          <div className="users-table">
            <table>
              <thead>
                <tr>
                  <th>Username</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Terminal</th>
                  <th>Department</th>
                  <th>Status</th>
                  <th>Created</th>
                  <th>Password</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {users.map(user => (
                  <tr key={user._id}>
                    <td>{user.username}</td>
                    <td>{user.firstName} {user.lastName}</td>
                    <td>{user.email || 'N/A'}</td>
                    <td>
                      <span className={`badge ${getRoleBadgeClass(user.role)}`}>
                        {formatRole(user.role)}
                      </span>
                    </td>
                    <td>
                      <span className={`badge ${getTerminalBadgeClass(user.terminal)}`}>
                        {user.terminal}
                      </span>
                    </td>
                    <td>{user.department || 'N/A'}</td>
                    <td>
                      <span className={`status-badge ${user.isActive ? 'active' : 'inactive'}`}>
                        {user.isActive ? 'Active' : 'Inactive'}
                      </span>
                    </td>
                    <td>{formatDate(user.createdAt)}</td>
                    <td>
                      <div className="password-info">
                        {user.autoGeneratedPassword && !user.isPasswordChanged ? (
                          <div className="password-display">
                            <span className="password-badge auto-generated">Auto-generated</span>
                            <span className="password-text" title="Click to copy" onClick={() => {
                              navigator.clipboard.writeText(user.autoGeneratedPassword);
                              alert('Password copied to clipboard!');
                            }}>
                              {user.autoGeneratedPassword}
                            </span>
                          </div>
                        ) : (
                          <span className="password-badge changed">Changed</span>
                        )}
                      </div>
                    </td>
                    <td>
                      <div className="action-buttons">
                        <RoleBasedAccess user={JSON.parse(localStorage.getItem('user') || '{}')} module="users" action="edit">
                          <button 
                            className="edit-btn"
                            onClick={() => handleEditUser(user)}
                          >
                            Edit
                          </button>
                        </RoleBasedAccess>
                        <RoleBasedAccess user={JSON.parse(localStorage.getItem('user') || '{}')} module="users" action="delete">
                          <button 
                            className="delete-btn"
                            onClick={() => handleDeleteUser(user._id)}
                          >
                            Delete
                          </button>
                        </RoleBasedAccess>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="pagination">
            <button 
              onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
              disabled={currentPage === 1}
              className="pagination-btn"
            >
              Previous
            </button>
            <span className="pagination-info">
              Page {currentPage} of {totalPages}
            </span>
            <button 
              onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
              disabled={currentPage === totalPages}
              className="pagination-btn"
            >
              Next
            </button>
          </div>
        )}

        {/* Add User Modal */}
        {showAddForm && (
          <div className="modal-overlay">
            <div className="modal">
              <div className="modal-header">
                <h3>Add New User</h3>
                <button 
                  className="close-btn"
                  onClick={() => setShowAddForm(false)}
                >
                  ×
                </button>
              </div>
              <form onSubmit={handleSubmit} className="add-user-form">
                <div className="form-group">
                  <label>Username:</label>
                  <input
                    type="text"
                    name="username"
                    value={newUser.username}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>First Name:</label>
                  <input
                    type="text"
                    name="firstName"
                    value={newUser.firstName}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Last Name:</label>
                  <input
                    type="text"
                    name="lastName"
                    value={newUser.lastName}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Email:</label>
                  <input
                    type="email"
                    name="email"
                    value={newUser.email}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Phone:</label>
                  <input
                    type="tel"
                    name="phone"
                    value={newUser.phone}
                    onChange={handleInputChange}
                    placeholder="Phone number"
                  />
                </div>
                <div className="form-group">
                  <label>Role:</label>
                  <select
                    name="role"
                    value={newUser.role}
                    onChange={handleInputChange}
                    required
                  >
                    <option value="admin">Admin</option>
                    <option value="garage_staff">Garage Staff</option>
                    <option value="transport_staff">Transport Staff</option>
                    <option value="inventory_staff">Inventory Staff</option>
                    <option value="driver">Driver</option>
                    <option value="customer_care">Customer Care</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Terminal:</label>
                  <select
                    name="terminal"
                    value={newUser.terminalId || newUser.terminal}
                    onChange={handleTerminalChange}
                    required
                  >
                    {terminals.map(t => (
                      <option key={String(t._id)} value={String(t._id)}>{t.name}</option>
                    ))}
                  </select>
                </div>
                <div className="form-group">
                  <label>Department:</label>
                  <select
                    name="department"
                    value={newUser.department}
                    onChange={handleInputChange}
                    required
                  >
                    <option value="management">Management</option>
                    <option value="garage">Garage</option>
                    <option value="transport">Transport</option>
                    <option value="inventory">Inventory</option>
                    <option value="drivers">Drivers</option>
                    <option value="customer_care">Customer Care</option>
                  </select>
                </div>
                <div className="form-actions">
                  <button type="submit" className="submit-btn">Add User</button>
                  <button 
                    type="button" 
                    className="cancel-btn"
                    onClick={() => setShowAddForm(false)}
                  >
                    Cancel
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Edit User Modal */}
        {showEditForm && editingUser && (
          <div className="modal-overlay">
            <div className="modal">
              <div className="modal-header">
                <h3>Edit User - {editingUser.firstName} {editingUser.lastName}</h3>
                <button 
                  className="close-btn"
                  onClick={() => setShowEditForm(false)}
                >
                  ×
                </button>
              </div>
              <form onSubmit={handleUpdateUser} className="edit-user-form">
                <div className="form-group">
                  <label>Username:</label>
                  <input
                    type="text"
                    name="username"
                    value={editingUser.username}
                    onChange={(e) => setEditingUser({...editingUser, username: e.target.value})}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>First Name:</label>
                  <input
                    type="text"
                    name="firstName"
                    value={editingUser.firstName}
                    onChange={(e) => setEditingUser({...editingUser, firstName: e.target.value})}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Last Name:</label>
                  <input
                    type="text"
                    name="lastName"
                    value={editingUser.lastName}
                    onChange={(e) => setEditingUser({...editingUser, lastName: e.target.value})}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Email:</label>
                  <input
                    type="email"
                    name="email"
                    value={editingUser.email}
                    onChange={(e) => setEditingUser({...editingUser, email: e.target.value})}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Phone:</label>
                  <input
                    type="tel"
                    name="phone"
                    value={editingUser.phone || ''}
                    onChange={(e) => setEditingUser({...editingUser, phone: e.target.value})}
                    placeholder="Phone number"
                  />
                </div>
                <div className="form-group">
                  <label>Role:</label>
                  <select
                    name="role"
                    value={editingUser.role}
                    onChange={(e) => setEditingUser({...editingUser, role: e.target.value})}
                    required
                  >
                    <option value="admin">Admin</option>
                    <option value="garage_staff">Garage Staff</option>
                    <option value="transport_staff">Transport Staff</option>
                    <option value="inventory_staff">Inventory Staff</option>
                    <option value="driver">Driver</option>
                    <option value="customer_care">Customer Care</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Terminal:</label>
                  <select
                    name="terminal"
                    value={editingUser.terminalId || editingUser.terminal}
                    onChange={(e) => {
                      const value = e.target.value;
                      const selected = terminals.find(t => String(t._id) === String(value) || t.name === value);
                      setEditingUser({
                        ...editingUser,
                        terminal: selected?.name || value,
                        terminalId: selected?._id || ''
                      });
                    }}
                    required
                  >
                    {terminals.map(t => (
                      <option key={String(t._id)} value={String(t._id)}>{t.name}</option>
                    ))}
                  </select>
                </div>
                <div className="form-group">
                  <label>Department:</label>
                  <select
                    name="department"
                    value={editingUser.department}
                    onChange={(e) => setEditingUser({...editingUser, department: e.target.value})}
                    required
                  >
                    <option value="management">Management</option>
                    <option value="garage">Garage</option>
                    <option value="transport">Transport</option>
                    <option value="inventory">Inventory</option>
                    <option value="drivers">Drivers</option>
                    <option value="customer_care">Customer Care</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Status:</label>
                  <select
                    name="isActive"
                    value={editingUser.isActive ? 'active' : 'inactive'}
                    onChange={(e) => setEditingUser({...editingUser, isActive: e.target.value === 'active'})}
                    required
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                  </select>
                </div>
                <div className="form-actions">
                  <button type="submit" className="submit-btn">Update User</button>
                  <button 
                    type="button" 
                    className="cancel-btn"
                    onClick={() => setShowEditForm(false)}
                  >
                    Cancel
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Password Change Modal */}
        {showPasswordChangeForm && selectedUser && (
          <div className="modal-overlay">
            <div className="modal">
              <div className="modal-header">
                <h3>Change Password - {selectedUser.firstName} {selectedUser.lastName}</h3>
                <button 
                  className="close-btn"
                  onClick={() => setShowPasswordChangeForm(false)}
                >
                  ×
                </button>
              </div>
              <form onSubmit={handlePasswordChangeSubmit} className="password-change-form">
                <div className="form-group">
                  <label>Current Password:</label>
                  <input
                    type="password"
                    name="currentPassword"
                    value={passwordChange.currentPassword}
                    onChange={handlePasswordChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>New Password:</label>
                  <input
                    type="password"
                    name="newPassword"
                    value={passwordChange.newPassword}
                    onChange={handlePasswordChange}
                    required
                    minLength={6}
                  />
                </div>
                <div className="form-group">
                  <label>Confirm New Password:</label>
                  <input
                    type="password"
                    name="confirmPassword"
                    value={passwordChange.confirmPassword}
                    onChange={handlePasswordChange}
                    required
                    minLength={6}
                  />
                </div>
                <div className="form-actions">
                  <button type="submit" className="submit-btn">Change Password</button>
                  <button 
                    type="button" 
                    className="cancel-btn"
                    onClick={() => setShowPasswordChangeForm(false)}
                  >
                    Cancel
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </RoleBasedAccess>
  );
};

export default Users;
